FROM rancher/os-debianconsole:v0.7.0
MAINTAINER Kevin M Meredith <https://github.com/KebinuChiousu>
#
# Update Packages and Install wget
RUN apt-get update && apt-get install -y wget
# Obtain version 0.5.0 of convoy docker volume plugin
RUN wget https://github.com/rancher/convoy/releases/download/v0.5.0/convoy.tar.gz /tmp/convoy.tar.gz
ADD convoy-start.sh /convoy-start.sh

RUN cp /tmp/convoy.tar.gz/convoy/convoy* /usr/bin/ \
    && rm -rf /tmp/convoy.tar.gz \
    && chmod +x /convoy-start.sh

ENTRYPOINT ["/convoy-start.sh"]